import { Button, VerticalBox } from "std-widgets.slint";

export component Sidebar inherits VerticalBox {   
    VerticalBox { 
        width: 20%;
        padding: 0px;

        Button {
            height: 30px;
            text: "Home";
        }
        Button {
            height: 30px;
            text: "Downloads";
        }
        Button {
            height: 30px;
            text: "Desktop";
        }
     }
}